### ISSUE TITLE
NLPModels rework steps

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#166]
On #109 I present the first version of a complete rework of NLPModels, but that quickly became difficult to review and too complex. I'll try to split the PR in smaller parts which provide a smooth transition to the full rework. Feedback is welcome.

- [x] (#167) Remove `Simple` models - it's better to create a specific model type;
- [x] (#169) Create specific model problems;
- [x] (#169) Document specific model;
- [ ] Prepare code for a better split
- [ ] (#187) Merge NLP and NLS;
- [ ] Refactor code - create api.jl;
- [ ] Add multiple single functions.

**Comment by abelsiqueira** [comment]
Apart from refactoring the code, the other points in this issue don't seem necessary for now. Merging NLP and NLS would fix some problems but create others, and there is no demand for it now.
