### ISSUE TITLE
NLPModels split checklist

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#337]
- [x] Core (Here)
  - [x] Separate code
  - [x] Create tests
  - [x] '>95%' coverage
  - [x] Documentation
  - [x] Release
- [x] Modifiers (https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl)
  - [x] Separate code
  - [x] Create tests
  - [x] '>95%' coverage
  - [x] Documentation
  - [x] Release
- [x] Test (https://github.com/JuliaSmoothOptimizers/NLPModelsTest.jl)
  - [x] Separate code
  - [x] Create tests
  - [x] '>95%' coverage
  - [x] Documentation
  - [x] Release
- [x] Move models
  - [x] ADNLPModels (https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/)
  - [x] LLSModels (https://github.com/JuliaSmoothOptimizers/LLSModels.jl/)
- [x] Update other main packages
  - [x] AmplNLReader
  - [x] CUTEst
  - [x] NLPModelsJuMP
  - [x] PDENLPModels
  - [x] QuadraticModels
